# Site
repository: tngh5004/tngh5004.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sooho Kim
title: Junior Deep-Learning Researcher and part-time Master's student
email: tngh5004@ajou.ac.kr
website: https://github.com/tngh5004

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  tngh5004
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: tngh5004
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0005-5925-9185

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sooho and I'm a junior Deep-Learning Researcher and part-time Master's student.  
  As well as developing and optimizing deep-learning models for mobile devices, I also have experience making image processing software.  
  I am a part-time graduate student and have published full papers in Top-tier AI conferences(MM2024).  

  Skill Set: Python, C++ <mark>High</mark> / Pytorch, OpenGL <mark>Middle</mark>

content:
  - title: Omnistitch # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Omnistitch:Depth-aware Stitching Framework for Omnidirectional Vision with Multiple Cameras
        link: https://doi.org/10.1145/3664647.3681208
        # link_text: Project Website
        additional_links:
          - title:  tngh5004/Omnistitch
            icon: fab fa-github
            url: https://github.com/tngh5004/Omnistitch
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a paper on Large parallax Omnidirectional image stitching. 
        description: | # this will include new lines to allow paragraphs
          Unlike previous work, the algorithm is designed to perform well even with <mark>large inter-camera distance parallaxes</mark>, and the paper provides a <mark>dataset(named GV360)</mark> for the study.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Quramsoft
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Junior Deep-Learning Researcher
        caption: July 2021 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ajou University
        caption: September 2022 - Present
        sub_title: Department of Artificial Intelligence 
        quote: >
          Established in 1971, Ajou University is a four-year comprehensive university located in Suwon, Gyeonggi-do, South Korea.
        description: | # this will include new lines to allow paragraphs
          I learned a lot about deep learning and met a lot of really nice people.
          I'm a part-time graduate student, so I didn't get to experience as much as I would have liked.
          I had a regular paper accepted as a first author at MM2024, a top-tier conference.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in deep-learning and software engineering some of my other interests and hobbies are:
      - Weight training
      - Reading a book 
      - Traveling
      - Swimming

      Look at this cool image  
      ![Snorkel](images/snorkeling.jpg "Snorkeling")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
